#ifndef GUIP_H
#define GUI_H

#include "ui_GUI.h"
/*
	As seen all the files of GUI ui_GUI.h is not in folder. While compiling "make" command will create it.
	This line is particularly important to understand. Our form created in designer is called GUI.ui. 
	Forms in .ui (XML) format are converted during build process into C++ header files by UIC (User Interface Compiler). 
	As Qt documentation says in the UIC documentation: The UIC reads an XML format user interface definition (.ui) file as generated by 
		Qt Designer and creates a corresponding C++ header file.
	hence ui_GUI.h file is created.
*/

class GUI : public QWidget, public Ui::GUIDLG
{
	public:
		Q_OBJECT
		QWidget *parent;
		int noof_txts,count;

	public:
		GUI();

	public slots:
		void getPathfolder();
		void getPathfile();
		void about();
		void ok();
		void quit();
		void yes();
		void no();
};

#endif
